export const paths = [
    "Modules/SPMI/Resources/assets/sass/target-indikator/create.scss",
    "Modules/SPMI/Resources/assets/sass/surat-tugas-auditor/create.scss",
    "Modules/SPMI/Resources/assets/sass/penilaian-audit/create.scss",
    "Modules/SPMI/Resources/assets/sass/indicator-table.scss",
    "Modules/SPMI/Resources/assets/sass/pengisian-indikator/create.scss",
    "Modules/SPMI/Resources/assets/js/pengisian-indikator/create.js",
    "Modules/SPMI/Resources/assets/js/pengisian-indikator-led/create.js",
    "Modules/SPMI/Resources/assets/sass/pengisian-indikator-led/create.scss",
    "Modules/SPMI/Resources/assets/sass/audit-temuan/create.scss",
    "Modules/SPMI/Resources/assets/sass/sk-auditor/create.scss",
    "Modules/SPMI/Resources/assets/sass/hasil-akhir-audit/create.scss",
    "Modules/SPMI/Resources/assets/sass/hasil-akhir-audit/report.scss",
    "Modules/SPMI/Resources/assets/sass/reports/show.scss",
    "Modules/SPMI/Resources/assets/sass/dashboard/index.scss",
    "Modules/SPMI/Resources/assets/sass/tinjauan-temuan/create.scss",
    "Modules/SPMI/Resources/assets/sass/reports/permintaan-tindakan-koreksi.scss",
    "Modules/SPMI/Resources/assets/sass/reports/default-laporan.scss"
];
